export const dynamic = "force-dynamic";

import CategoryCard from "@/components/frontend/CategoryCard";
import CouponCard from "@/components/frontend/CouponCard";
import StoreCard from "@/components/frontend/StoreCard";
import BlogCards from "@/components/frontend/BlogCards";
import { prisma } from "@/lib/prisma";
import { ArrowRight, BadgePercent, CheckCircle2, Flame, Search, ShieldCheck, Sparkles, Tag, TrendingUp, WalletCards } from "lucide-react";
import Link from "next/link";

export default async function HomePage() {
  const [categories, stores, coupons, blogs] = await Promise.all([
    prisma.category.findMany({ orderBy: [{ sortOrder: "asc" }, { createdAt: "asc" }], take: 8 }),
    prisma.store.findMany({ where: { featured: true }, orderBy: [{ sortOrder: "asc" }, { rating: "desc" }], take: 4 }),
    prisma.coupon.findMany({ where: { featured: true }, orderBy: [{ sortOrder: "asc" }, { clicks: "desc" }], take: 6 }),
    prisma.blog.findMany({ orderBy: [{ sortOrder: "asc" }, { createdAt: "desc" }], take: 3 }),
  ]);
  const [totalStores, totalCoupons] = await Promise.all([prisma.store.count(), prisma.coupon.count()]);
  return (
    <main>
      <section className="relative overflow-hidden bg-gradient-to-br from-[#fff7ed] via-[#f0fdfa] to-[#fef3c7] px-4 py-20">
        <div className="absolute -right-24 -top-24 h-80 w-80 rounded-full bg-orange-300/30 blur-3xl" />
        <div className="absolute -bottom-24 -left-24 h-80 w-80 rounded-full bg-teal-300/30 blur-3xl" />
        <div className="relative mx-auto grid max-w-7xl items-center gap-12 lg:grid-cols-2">
          <div>
            <span className="inline-flex items-center gap-2 rounded-full bg-white px-4 py-2 text-sm font-black text-orange-600 shadow-sm"><Sparkles size={16} /> Verified Coupons & Affiliate Deals</span>
            <h1 className="mt-6 text-5xl font-black leading-tight text-slate-950 md:text-7xl">Save More With <span className="block text-teal-700">Saving Trendz</span></h1>
            <p className="mt-6 max-w-xl text-lg leading-8 text-slate-600">Saving Trendz helps shoppers discover reliable promo codes, affiliate deals, store discounts and category-based offers without wasting time on expired coupons.</p>
            <form action="/coupons" className="mt-8 flex max-w-xl overflow-hidden rounded-2xl border border-orange-100 bg-white p-2 shadow-xl"><div className="flex flex-1 items-center gap-3 px-4"><Search className="text-slate-400" size={20}/><input name="q" placeholder="Search stores, coupons or categories..." className="w-full bg-transparent text-sm outline-none"/></div><button className="rounded-xl bg-orange-500 px-6 py-3 text-sm font-black text-white transition hover:bg-orange-600">Search</button></form>
            <div className="mt-8 grid max-w-xl grid-cols-3 gap-4"><div className="rounded-2xl bg-white p-4 shadow-sm"><h3 className="text-2xl font-black">{totalCoupons}+</h3><p className="text-xs font-bold text-slate-500">Deals</p></div><div className="rounded-2xl bg-white p-4 shadow-sm"><h3 className="text-2xl font-black">{totalStores}+</h3><p className="text-xs font-bold text-slate-500">Stores</p></div><div className="rounded-2xl bg-white p-4 shadow-sm"><h3 className="text-2xl font-black">Daily</h3><p className="text-xs font-bold text-slate-500">Updates</p></div></div>
          </div>
          <div className="rounded-[2rem] bg-slate-950 p-6 text-white shadow-2xl md:p-8"><div className="flex items-center justify-between"><div className="flex items-center gap-3"><div className="rounded-2xl bg-orange-500 p-3"><Tag/></div><div><p className="text-sm text-slate-400">Today’s Hot Picks</p><h2 className="text-2xl font-black">Top Verified Offers</h2></div></div><span className="rounded-full bg-teal-500/20 px-3 py-1 text-xs font-black text-teal-300">Live</span></div><div className="mt-8 space-y-4">{coupons.slice(0,3).map(c=><div key={c.id} className="rounded-3xl border border-white/10 bg-white/10 p-5"><div className="flex items-center justify-between gap-4"><div><h3 className="font-black">{c.discount} at {c.store}</h3><p className="mt-1 text-sm text-slate-400">{c.title}</p></div><Link href="/coupons" className="rounded-xl bg-white px-4 py-2 text-xs font-black text-slate-950">Get Code</Link></div></div>)}</div></div>
        </div>
      </section>
      <section className="mx-auto max-w-7xl px-4 py-14"><div className="grid gap-5 md:grid-cols-4"><div className="rounded-3xl bg-white p-6 shadow-sm"><ShieldCheck className="text-teal-700"/><h3 className="mt-4 text-lg font-black">Verified Codes</h3><p className="mt-2 text-sm text-slate-500">Coupons are organized and reviewed before publishing.</p></div><div className="rounded-3xl bg-white p-6 shadow-sm"><Flame className="text-orange-500"/><h3 className="mt-4 text-lg font-black">Trending Offers</h3><p className="mt-2 text-sm text-slate-500">Fresh deals from popular stores and categories.</p></div><div className="rounded-3xl bg-white p-6 shadow-sm"><WalletCards className="text-teal-700"/><h3 className="mt-4 text-lg font-black">Affiliate Friendly</h3><p className="mt-2 text-sm text-slate-500">Each store can point users to affiliate shopping links.</p></div><div className="rounded-3xl bg-white p-6 shadow-sm"><CheckCircle2 className="text-emerald-600"/><h3 className="mt-4 text-lg font-black">Easy Savings</h3><p className="mt-2 text-sm text-slate-500">Copy code, visit store and shop smarter.</p></div></div></section>
      <section className="mx-auto max-w-7xl px-4 py-14"><div className="mb-8 flex items-end justify-between"><div><p className="font-black text-orange-500">Shop By Category</p><h2 className="mt-2 text-4xl font-black">Popular Categories</h2></div><Link href="/categories" className="hidden items-center gap-2 rounded-full bg-slate-950 px-5 py-3 text-sm font-black text-white md:flex">View All <ArrowRight size={16}/></Link></div><div className="grid gap-6 sm:grid-cols-2 lg:grid-cols-4">{categories.map(c=><CategoryCard key={c.id} {...c}/>)}</div></section>
      <section className="bg-white/50 px-4 py-16"><div className="mx-auto grid max-w-7xl items-center gap-10 lg:grid-cols-[1fr_1.2fr]"><div><p className="font-black text-orange-500">How It Works</p><h2 className="mt-2 text-4xl font-black text-slate-950">Affiliate savings made simple</h2><p className="mt-4 leading-7 text-slate-600">Saving Trendz gives shoppers a clean way to browse stores, compare categories, copy promo codes and open store offers.</p></div><div className="grid gap-4 md:grid-cols-3">{["Find a store","Copy a coupon","Shop & save"].map((item,i)=><div key={item} className="rounded-3xl border border-orange-100 bg-white p-6 shadow-sm"><div className="flex h-12 w-12 items-center justify-center rounded-2xl bg-teal-50 text-xl font-black text-teal-700">{i+1}</div><h3 className="mt-4 font-black">{item}</h3><p className="mt-2 text-sm leading-6 text-slate-500">{i===0?"Browse trusted stores and categories.":i===1?"Use a verified code or direct deal.":"Visit the store and complete checkout."}</p></div>)}</div></div></section>
      <section className="mx-auto max-w-7xl px-4 py-14"><div className="mb-8 flex items-end justify-between"><div><p className="font-black text-orange-500">Featured Stores</p><h2 className="mt-2 text-4xl font-black">Top Coupon Stores</h2></div><Link href="/stores" className="hidden items-center gap-2 rounded-full bg-teal-700 px-5 py-3 text-sm font-black text-white md:flex">All Stores <ArrowRight size={16}/></Link></div><div className="grid gap-6 sm:grid-cols-2 lg:grid-cols-4">{stores.map(s=><StoreCard key={s.id} {...s}/>)}</div></section>
      <section className="mx-auto max-w-7xl px-4 py-14"><div className="mb-8 flex items-end justify-between"><div><p className="font-black text-orange-500">Latest Coupons</p><h2 className="mt-2 text-4xl font-black">Fresh Promo Codes</h2></div><Link href="/coupons" className="hidden items-center gap-2 rounded-full bg-orange-500 px-5 py-3 text-sm font-black text-white md:flex">View Coupons <BadgePercent size={16}/></Link></div><div className="grid gap-6 lg:grid-cols-3">{coupons.map(c=><CouponCard key={c.id} {...c}/>)}</div></section>
      <section className="mx-auto max-w-7xl px-4 py-14"><div className="rounded-[2rem] bg-gradient-to-br from-teal-700 to-slate-950 p-8 text-white shadow-xl md:p-12"><div className="grid items-center gap-8 md:grid-cols-2"><div><p className="font-black text-orange-300">Saving Trendz Promise</p><h2 className="mt-3 text-4xl font-black">Built for shoppers and affiliate growth</h2><p className="mt-4 text-slate-200">The website is designed to help visitors quickly find the right offer while giving the admin simple control over content, stores and coupon updates.</p></div><div className="grid gap-4 sm:grid-cols-2"><div className="rounded-3xl bg-white/10 p-5"><TrendingUp/><h3 className="mt-3 font-black">SEO Ready Pages</h3></div><div className="rounded-3xl bg-white/10 p-5"><BadgePercent/><h3 className="mt-3 font-black">Coupon Focused UI</h3></div></div></div></div></section>
      <section className="mx-auto max-w-7xl px-4 py-14"><div className="mb-8"><p className="font-black text-orange-500">Guides</p><h2 className="mt-2 text-4xl font-black">Shopping & Saving Tips</h2></div><BlogCards compact blogs={blogs.map((b) => ({ id: b.id, title: b.title, category: b.category, content: b.content, excerpt: b.excerpt, imageUrl: b.imageUrl, date: b.date, readTime: b.readTime }))} /></section>
    </main>
  );
}
